services:
  db:
    image: postgres:16-alpine
    container_name: ipl_fantasy_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: fantasy
      POSTGRES_PASSWORD: fantasy_secret
      POSTGRES_DB: ipl_fantasy
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ipl_fantasy_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
